/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiPublicOpenaqRouteImport } from './routes/api/public/openaq'
import { Route as ApiPublicFirmsRouteImport } from './routes/api/public/firms'
import { Route as ApiPublicEnsoRouteImport } from './routes/api/public/enso'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOpenaqRoute = ApiPublicOpenaqRouteImport.update({
  id: '/api/public/openaq',
  path: '/api/public/openaq',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicFirmsRoute = ApiPublicFirmsRouteImport.update({
  id: '/api/public/firms',
  path: '/api/public/firms',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicEnsoRoute = ApiPublicEnsoRouteImport.update({
  id: '/api/public/enso',
  path: '/api/public/enso',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/enso': typeof ApiPublicEnsoRoute
  '/api/public/firms': typeof ApiPublicFirmsRoute
  '/api/public/openaq': typeof ApiPublicOpenaqRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/enso': typeof ApiPublicEnsoRoute
  '/api/public/firms': typeof ApiPublicFirmsRoute
  '/api/public/openaq': typeof ApiPublicOpenaqRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/api/public/enso': typeof ApiPublicEnsoRoute
  '/api/public/firms': typeof ApiPublicFirmsRoute
  '/api/public/openaq': typeof ApiPublicOpenaqRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sitemap.xml'
    | '/api/public/enso'
    | '/api/public/firms'
    | '/api/public/openaq'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sitemap.xml'
    | '/api/public/enso'
    | '/api/public/firms'
    | '/api/public/openaq'
  id:
    | '__root__'
    | '/'
    | '/sitemap.xml'
    | '/api/public/enso'
    | '/api/public/firms'
    | '/api/public/openaq'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  ApiPublicEnsoRoute: typeof ApiPublicEnsoRoute
  ApiPublicFirmsRoute: typeof ApiPublicFirmsRoute
  ApiPublicOpenaqRoute: typeof ApiPublicOpenaqRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/openaq': {
      id: '/api/public/openaq'
      path: '/api/public/openaq'
      fullPath: '/api/public/openaq'
      preLoaderRoute: typeof ApiPublicOpenaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/firms': {
      id: '/api/public/firms'
      path: '/api/public/firms'
      fullPath: '/api/public/firms'
      preLoaderRoute: typeof ApiPublicFirmsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/enso': {
      id: '/api/public/enso'
      path: '/api/public/enso'
      fullPath: '/api/public/enso'
      preLoaderRoute: typeof ApiPublicEnsoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  ApiPublicEnsoRoute: ApiPublicEnsoRoute,
  ApiPublicFirmsRoute: ApiPublicFirmsRoute,
  ApiPublicOpenaqRoute: ApiPublicOpenaqRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
